[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/MMMejias39/RGPU"
authors = ["Marcelo Mejias <mmmejias39@gmail.com>"]

[workspace.dependencies]
wgpu = "30"
pollster = "0.4"
bytemuck = { version = "1", features = ["derive"] }

[profile.release]
opt-level = 3
